"use client";

import { ErrorBoundary } from "@/components/shared/error-boundary";
import { DigestStateGate } from "@/components/digest/DigestStateGate";
import { useRepositoryDigest } from "@/lib/hooks/useRepositoryDigest";
import type {
  DigestAnnotatedDirectory,
  DigestEntrypoint,
  DigestReadingPathItem,
} from "@/lib/graphql/queries/repository-digest";

export default function DigestStartPage() {
  const { digest, fetching, error, status, refreshing, refreshError, dismissRefreshError, handleRefresh } =
    useRepositoryDigest();

  return (
    <ErrorBoundary>
      <div className="digest-page-title">Start here</div>
      <DigestStateGate
        fetching={fetching}
        error={error}
        digest={digest}
        status={status}
        refreshing={refreshing}
        refreshError={refreshError}
        onDismissRefreshError={dismissRefreshError}
        onRefresh={handleRefresh}
        emptyMessage="The project map contains no indexed files. Entrypoints and structure will populate once the repository has content."
      >
        {(d) => (
          <>
            <Entrypoints entrypoints={d.entrypoints} />
            <ReadingPath items={d.readingPath} />
            <AnnotatedTree tree={d.annotatedTree} />
          </>
        )}
      </DigestStateGate>
    </ErrorBoundary>
  );
}

/**
 * An entrypoint here is a file a discovered RUN/DEVELOP command's own
 * text actually names (lib/context/repository_digest_extras.py:
 * derive_entrypoints) — never a filename-convention guess.
 */
function Entrypoints({ entrypoints }: { entrypoints: DigestEntrypoint[] }) {
  return (
    <div className="surface" style={{ padding: 20 }}>
      <div className="type-section-title" style={{ marginBottom: 12 }}>
        Entrypoints
      </div>
      {entrypoints.length === 0 ? (
        <p className="type-body">
          No entrypoint could be confirmed — no discovered run/develop command names a file that exists in this
          repository.
        </p>
      ) : (
        <div className="digest-kpi-grid">
          {entrypoints.map((e, i) => (
            <div key={i} className="surface-elevated" style={{ padding: 16, borderRadius: 8 }}>
              <div className="type-caption" style={{ textTransform: "uppercase" }}>{e.kind}</div>
              <div className="type-mono-value" style={{ marginTop: 4, wordBreak: "break-all" }}>{e.file}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function ReadingPath({ items }: { items: DigestReadingPathItem[] }) {
  return (
    <div className="surface" style={{ padding: 20 }}>
      <div className="type-section-title" style={{ marginBottom: 4 }}>
        Suggested reading path
      </div>
      <p className="type-caption" style={{ marginBottom: 12 }}>
        Deterministic, evidence-backed order — not generated by a model.
      </p>
      {items.length === 0 ? (
        <p className="type-body">Not enough evidence (documentation, manifest, entrypoints, or domains) to suggest a reading order yet.</p>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {items.map((item, i) => (
            <div key={i} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
              <div
                className="type-mono-value"
                style={{
                  flexShrink: 0, width: 22, height: 22, borderRadius: "50%",
                  border: "1px solid var(--color-border)", display: "flex", alignItems: "center",
                  justifyContent: "center", fontSize: 11, color: "var(--color-text-secondary)",
                }}
              >
                {i + 1}
              </div>
              <div>
                <div className="type-mono-value">{item.file}</div>
                <p className="type-column-intent" style={{ margin: "2px 0 0" }}>{item.reason}</p>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * Top-level directories from project-map.json's own directory stats,
 * each optionally annotated with whichever domain owns the most files
 * under it. No description is invented for a directory no domain
 * claims — it just shows the file/line counts on their own.
 */
function AnnotatedTree({ tree }: { tree: DigestAnnotatedDirectory[] }) {
  return (
    <div className="surface" style={{ padding: 20 }}>
      <div className="type-section-title" style={{ marginBottom: 12 }}>
        Repository structure
      </div>
      {tree.length === 0 ? (
        <p className="type-body">No top-level directory structure available.</p>
      ) : (
        <div className="digest-table-scroll">
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <tbody>
              {tree.map((d, i) => (
                <tr key={d.path} style={{ borderTop: i > 0 ? "1px solid var(--color-border-light)" : undefined }}>
                  <td className="type-mono-value" style={{ padding: "10px 12px 10px 0", whiteSpace: "nowrap" }}>{d.path}/</td>
                  <td className="type-column-intent" style={{ padding: "10px 12px 10px 0" }}>
                    {d.dominantDomainLabel ?? "—"}
                  </td>
                  <td className="type-caption" style={{ padding: "10px 0", textAlign: "right", whiteSpace: "nowrap" }}>
                    {d.fileCount.toLocaleString()} files · {d.totalLines.toLocaleString()} lines
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
