"""Versioned business-domain contracts, safe artifact IO and configuration.

Domain records are a language-independent interpretation. This module never
executes target code or invokes a semantic provider.
"""
from __future__ import annotations

import copy
import hashlib
import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker

SCHEMA_PATH = Path(__file__).with_name('business_domain_artifacts.schema.json')
SCHEMA = json.loads(SCHEMA_PATH.read_text())
DEFINITIONS = SCHEMA['$defs']
DEFAULTS = json.loads(Path(__file__).with_name('business_domain_defaults.json').read_text())
ACCOUNTING_POLICY = json.loads(Path(__file__).with_name('business_domain_policies.json').read_text())
REFERENCE_TARGETS = json.loads(Path(__file__).with_name('business_domain_reference_targets.json').read_text())
COLLECTIONS = {
    'resource': 'resources', 'symbol': 'symbols', 'edge': 'edges', 'anchor': 'anchors',
    'binding': 'bindings', 'trace': 'traces', 'effect': 'effects', 'ev': 'evidence',
    'trace_obligation': 'trace_obligations',
    'snapshot': 'source_snapshots', 'observation': 'rule_observations',
    'activity': 'activities', 'concept': 'concepts', 'information_use': 'information_uses',
    'ownership': 'ownerships', 'rule': 'rules', 'rule_relationship': 'rule_relationships',
    'claim': 'claims', 'domain': 'domains', 'relationship': 'relationships',
}


class DomainError(ValueError):
    def __init__(self, code: str, message: str, field: str | None = None, *,
                 retryable: bool = False, provider_failure: dict | None = None,
                 findings: list[dict] | None = None,
                 rejected_candidate: Any = None,
                 repair_kind: str | None = None,
                 verification_report: Any = None):
        super().__init__(message)
        self.code, self.field = code, field
        self.retryable = retryable
        self.provider_failure = copy.deepcopy(provider_failure)
        # Repair context is intentionally process-local. Public status errors
        # must never persist an untrusted provider response.
        self.findings = copy.deepcopy(findings or [])
        self.rejected_candidate = copy.deepcopy(rejected_candidate)
        self.repair_kind = repair_kind
        self.verification_report = copy.deepcopy(verification_report)

    def record(self) -> dict:
        return {'code': self.code, 'message': str(self), 'field': self.field,
                'retryable': self.retryable,
                'provider_failure': copy.deepcopy(self.provider_failure)}


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False, allow_nan=False).encode()


def digest(value: Any) -> str:
    return hashlib.sha256(value if isinstance(value, bytes) else canonical(value)).hexdigest()


def identifier(kind: str, *parts: Any) -> str:
    return f'{kind}:{digest(parts)[:24]}'


def implementation_hash(*locations: Path) -> str:
    """Hash installed implementation inputs, excluding generated bytecode."""
    files = {}
    for location in locations:
        candidates = location.rglob('*') if location.is_dir() else [location]
        for path in candidates:
            if path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc':
                name = str(path.relative_to(location)) if location.is_dir() else path.name
                files[location.name + '/' + name] = digest(path.read_bytes())
    return digest(files)


def _default(schema: dict) -> Any:
    if '$ref' in schema:
        return _default(DEFINITIONS[schema['$ref'].rsplit('/', 1)[1]])
    if 'anyOf' in schema:
        return None
    if 'oneOf' in schema:
        return _default(schema['oneOf'][0])
    if 'const' in schema:
        return schema['const']
    if 'enum' in schema:
        return schema['enum'][0]
    kind = schema.get('type')
    if kind == 'object':
        return {key: _default(value) for key, value in schema.get('properties', {}).items()}
    if kind == 'array':
        return []
    if kind == 'integer':
        return schema.get('minimum', 0)
    if kind == 'boolean':
        return False
    return ''


def record(type_name: str, **values: Any) -> dict:
    """Construct required nullable/empty fields; validate at the boundary."""
    if type_name in ('Anchor', 'Edge') and values.get('resolution') not in DEFINITIONS[type_name]['properties']['resolution']['enum']:
        raise DomainError('INVALID_ARTIFACT', f'{type_name}: producer must supply explicit resolution', 'resolution')
    result = _default(DEFINITIONS[type_name])
    result.update(values)
    return result


def settings(config: dict | None) -> dict:
    raw = (config or {}).get('business_domains', {})
    if not isinstance(raw, dict) or set(raw) - set(DEFAULTS):
        raise DomainError('INVALID_CONFIG', 'Unknown or invalid business_domains configuration')
    result = {**DEFAULTS, **raw}
    for key, value in result.items():
        if key == 'snapshot_manifest':
            if value is not None and (not isinstance(value, str) or not value.strip()):
                raise DomainError('INVALID_CONFIG', f'{key} must be null or a nonempty string', key)
        elif type(value) is not int or value < 1:
            raise DomainError('INVALID_CONFIG', f'{key} must be a positive integer', key)
    if result['max_trace_depth'] > 20 or result['provider_concurrency'] > 4:
        raise DomainError('INVALID_CONFIG', 'Trace depth or provider concurrency exceeds supported limit')
    for resource in ('input', 'output'):
        if result[f'max_request_{resource}_tokens'] > result[f'max_build_{resource}_tokens']:
            raise DomainError('INVALID_CONFIG', 'Per-request token cap exceeds build cap')
    return result


def limits(config: dict) -> dict:
    configured = {key: value for key, value in config.items()
                  if key in DEFINITIONS['Limits']['properties']}
    configured.update({
        'token_estimator': ACCOUNTING_POLICY['token_estimator'],
        'provider_context_tokens': None,
        'provider_max_output_tokens': None,
        'effective_request_input_tokens': config['max_request_input_tokens'],
        'effective_request_output_tokens': config['max_request_output_tokens'],
        'semantic_units_total': 0,
        'semantic_units_validated': 0,
        'semantic_units_cached': 0,
        'semantic_units_active': 0,
        'semantic_units_failed': 0,
        'semantic_units_pending': 0,
        'model_ready_graph_tokens': 0,
        'completion_input_tokens_reserved': 0,
        'completion_output_tokens_reserved': 0,
    })
    return record('Limits', **configured)


def account_artifact_bytes(value: dict) -> int:
    """Record the exact self-inclusive canonical size of a limited artifact."""
    while True:
        measured = len(canonical(value))
        if value['limits']['artifact_bytes'] == measured:
            return measured
        value['limits']['artifact_bytes'] = measured


def validation_findings(value: Any, schema: dict, label: str,
                        code: str = 'INVALID_ARTIFACT') -> list[dict]:
    """Return every schema failure in the normative repair finding shape."""
    errors = sorted(
        Draft202012Validator(schema, format_checker=FormatChecker()).iter_errors(value),
        key=lambda error: (tuple(str(part) for part in error.absolute_path),
                           error.validator, error.message),
    )
    findings = []
    for error in errors:
        field = '.'.join(map(str, error.absolute_path)) or '$'
        findings.append({
            'code': code,
            'severity': 'error',
            'message': f'{label}: invalid {error.validator} at {field}',
            'subject_ids': [],
            'evidence_ids': [],
        })
    return findings


def validation_finding(code: str, message: str, *, subject_ids=(),
                       evidence_ids=()) -> dict:
    """Build one deterministic finding without leaking arbitrary values."""
    return {'code': code, 'severity': 'error', 'message': message,
            'subject_ids': sorted(set(subject_ids)),
            'evidence_ids': sorted(set(evidence_ids))}


def reject_findings(findings: list[dict]) -> None:
    """Raise one repairable error carrying every independently found defect."""
    if findings:
        first = findings[0]
        raise DomainError(first['code'], first['message'], findings=findings,
                          repair_kind='semantic')


def required_scope_subjects(graph: dict) -> dict[str, str]:
    """Return every subject synthesis and verification must account for."""
    if graph['scope_kind'] == 'reconciliation':
        return {subject_id: 'child_scope'
                for subject_id in graph['child_scope_ids']}
    required = {subject_id: 'anchor'
                for subject_id in graph['canonical_anchor_ids']}
    supplied_representations = set(graph['source_representation_ids'])
    for subject_id, correspondence in graph['context'][
            'anchor_correspondences'].items():
        representations = {
            correspondence['from_representation'],
            *correspondence['to_representations'],
        }
        if (correspondence['state'] in ('ambiguous', 'unresolved')
                and representations & supplied_representations):
            required[subject_id] = 'anchor_correspondence'
    return required


def candidate_scope_findings(graph: dict, candidate: dict) -> list[dict]:
    """Return all mechanically provable scope/disposition failures."""
    findings = []
    required = required_scope_subjects(graph)
    if candidate['scope_id'] != graph['scope_id']:
        findings.append(validation_finding(
            'INVALID_COVERAGE', 'Candidate belongs to a different graph scope',
            subject_ids=[candidate['scope_id']]))
    if candidate['input_fingerprint'] != graph['input_fingerprint']:
        findings.append(validation_finding(
            'INVALID_COVERAGE',
            'Candidate input fingerprint differs from its graph scope'))

    by_subject = {}
    for disposition in candidate['dispositions']:
        by_subject.setdefault(disposition['subject_id'], []).append(disposition)
    missing = set(required)-set(by_subject)
    extra = set(by_subject)-set(required)
    duplicates = {subject_id for subject_id, values in by_subject.items()
                  if len(values) != 1}
    if missing or extra or duplicates:
        findings.append(validation_finding(
            'INVALID_COVERAGE',
            'Candidate requires exactly one disposition per scope subject',
            subject_ids=missing | extra | duplicates))

    activity_ids = set(candidate['activities'])
    memberships = {}
    for activity in candidate['activities'].values():
        for anchor_id in activity['anchor_ids']:
            memberships.setdefault(anchor_id, set()).add(activity['id'])
        outside = set(activity['anchor_ids'])-set(graph['canonical_anchor_ids'])
        if outside:
            findings.append(validation_finding(
                'INVALID_COVERAGE',
                'Activity contains an anchor outside its graph scope',
                subject_ids=[activity['id'], *outside]))

    for subject_id, values in by_subject.items():
        if len(values) != 1 or subject_id not in required:
            continue
        disposition = values[0]
        if disposition['subject_kind'] != required[subject_id]:
            findings.append(validation_finding(
                'INVALID_COVERAGE', 'Disposition subject kind is incorrect',
                subject_ids=[subject_id]))
        invalid = set(disposition['activity_ids'])-activity_ids
        if invalid:
            findings.append(validation_finding(
                'INVALID_REFERENCE',
                'Disposition refers to an activity absent from the candidate',
                subject_ids=[subject_id, *invalid]))
        if required[subject_id] == 'anchor' and \
                set(disposition['activity_ids']) != memberships.get(subject_id, set()):
            findings.append(validation_finding(
                'INVALID_MEMBERSHIP',
                'Anchor disposition and Activity.anchor_ids disagree',
                subject_ids=[subject_id, *disposition['activity_ids'],
                             *memberships.get(subject_id, set())]))

    required_anchor_ids = {
        subject_id for subject_id, subject_kind in required.items()
        if subject_kind == 'anchor'
    }
    evidenced_exclusions = {
        subject_id for subject_id, dispositions in by_subject.items()
        if subject_id in required_anchor_ids
        and len(dispositions) == 1
        and dispositions[0]['subject_kind'] == 'anchor'
        and dispositions[0]['status'] == 'excluded'
        and dispositions[0]['evidence_ids']
    }
    if (required_anchor_ids and not candidate['activities']
            and evidenced_exclusions != required_anchor_ids):
        findings.append(validation_finding(
            'VACUOUS_BUSINESS_MODEL',
            ('A zero-activity candidate must independently exclude every '
             'canonical anchor with evidence'),
            subject_ids=required_anchor_ids-evidenced_exclusions))
    return findings


def verification_report_findings(graph: dict, report: dict) -> list[dict]:
    """Return deterministic verifier-envelope and coverage failures."""
    findings = []
    if report['scope_id'] != graph['scope_id']:
        findings.append(validation_finding(
            'INVALID_REVIEW', 'Verification report belongs to another scope'))
    if report['input_fingerprint'] != graph['input_fingerprint']:
        findings.append(validation_finding(
            'INVALID_REVIEW',
            'Verification report fingerprint differs from its graph scope'))
    required = set(required_scope_subjects(graph))
    checked = set(report['checked_subject_ids'])
    if checked != required:
        findings.append(validation_finding(
            'INVALID_REVIEW',
            'Verifier must check every required scope subject',
            subject_ids=required ^ checked))
    blocking = any(finding['severity'] == 'blocking'
                   for finding in report['findings'])
    if report['verdict'] == 'pass' and blocking:
        findings.append(validation_finding(
            'INVALID_REVIEW',
            'Passing verification cannot contain a blocking finding'))
    if report['verdict'] != 'pass' and not blocking:
        findings.append(validation_finding(
            'INVALID_REVIEW',
            'Non-passing verification requires a blocking finding'))
    return findings


def validate(value: dict, type_name: str) -> None:
    schema = {'$schema': SCHEMA['$schema'], '$defs': DEFINITIONS,
              '$ref': '#/$defs/' + type_name}
    findings = validation_findings(value, schema, type_name)
    if findings:
        message = findings[0]['message']
        field = message.rsplit(' at ', 1)[-1]
        raise DomainError('INVALID_ARTIFACT', message, field,
                          findings=findings, rejected_candidate=value,
                          repair_kind='schema')


def activity_closure(model: dict, activity: dict) -> dict[str, set[str]]:
    """Canonical operation membership for hydration and integrity validation."""
    traces = set(activity['trace_ids'])
    symbols = {sid for tid in traces for sid in model['traces'][tid]['symbol_ids']}
    edge_ids = {eid for tid in traces for eid in model['traces'][tid]['edge_ids']}
    operation_binding_ids = {bid for eid in edge_ids
        for bid in model['edges'][eid].get('binding_ids', [])}
    closure = {'effect_ids': {eid for eid, effect in model['effects'].items()
               if set(effect['trace_ids']) & traces},
               'information_use_ids': {iid for iid, use in model.get('information_uses', {}).items()
               if use['activity_id'] == activity['id']}}
    for direction in ('input', 'output'):
        closure[direction+'_binding_ids'] = {bid for bid, binding in model['bindings'].items()
            if binding['direction'] == direction and binding['source']
            and ((binding['source']['kind'] == 'symbol'
                  and binding['source']['id'] in symbols)
                 or bid in operation_binding_ids)}
    return closure


def implementation_symbol_memberships(model: dict, activity_ids) -> list[dict]:
    """Derive domain symbols only from satisfied implementation selections."""
    memberships = []
    for activity_id in sorted(set(activity_ids)):
        for trace_id in model['activities'][activity_id]['trace_ids']:
            trace = model['traces'][trace_id]
            implementations = {
                symbol_id
                for obligation_id in trace.get('obligation_ids', [])
                for obligation in [model.get('trace_obligations', {}).get(obligation_id, {})]
                if obligation.get('kind') == 'implementation_selection'
                and obligation.get('status') == 'satisfied'
                for symbol_id in obligation['candidate_target_ids']
            }
            for symbol_id in sorted(implementations):
                memberships.append(record(
                    'SymbolMembership', symbol_id=symbol_id,
                    activity_id=activity_id, role='implements', trace_ids=[trace_id],
                ))
    return memberships


def information_use_closure(model: dict, use: dict) -> dict[str, set[str]]:
    """Deterministic graph closure for a provider-selected resource use."""
    activity = model['activities'].get(use['activity_id'])
    if not activity or use['concept_id'] not in activity['concept_ids']:
        raise DomainError('INVALID_REFERENCE', 'Information use must belong to its activity and concept')
    resources = set(use['resource_ids'])
    if not resources:
        raise DomainError('INVALID_REFERENCE', 'Information use requires an evidenced resource')
    kinds = {'reads': {'reads_data'},
             'creates': {'writes_data'}, 'updates': {'writes_data'}, 'deletes': {'writes_data'},
             'references': {'reads_data', 'writes_data'}}[use['access']]
    traces = {tid: model['traces'][tid] for tid in activity['trace_ids']}
    edge_ids = {eid for trace in traces.values() for eid in trace['edge_ids']
                if model['edges'][eid]['kind'] in kinds
                and model['edges'][eid]['to_ref']
                and model['edges'][eid]['to_ref']['kind'] == 'resource'
                and model['edges'][eid]['to_ref']['id'] in resources}
    reached_resources = {model['edges'][eid]['to_ref']['id'] for eid in edge_ids}
    if reached_resources != resources:
        raise DomainError('INVALID_REFERENCE', 'Information use resource is outside its activity operation closure')
    trace_ids = {tid for tid, trace in traces.items() if edge_ids & set(trace['edge_ids'])}
    binding_ids = {bid for eid in edge_ids for bid in model['edges'][eid]['binding_ids']}
    effect_ids = {effect['id'] for effect in model['effects'].values()
                  if effect.get('edge_id') in edge_ids}
    evidence_ids = {evidence for eid in edge_ids for evidence in model['edges'][eid]['evidence_ids']}
    evidence_ids.update(evidence for bid in binding_ids for evidence in model['bindings'][bid]['evidence_ids'])
    evidence_ids.update(evidence for eid in effect_ids for evidence in model['effects'][eid]['evidence_ids'])
    return {'edge_ids': edge_ids, 'trace_ids': trace_ids, 'binding_ids': binding_ids,
            'effect_ids': effect_ids, 'evidence_ids': evidence_ids}


def validate_references(model: dict) -> None:
    records: dict[str, dict] = {}
    kinds: dict[str,str] = {}
    for kind,collection in COLLECTIONS.items():
        for key, item in model.get(collection, {}).items():
            if key != item['id'] or key in records:
                raise DomainError('INVALID_REFERENCE', 'Duplicate record ID or mismatched map key')
            records[key] = item
            kinds[key] = kind
    # Anchor representations and correspondences are embedded so a canonical
    # anchor remains a self-contained serialization unit.  They are still
    # first-class records for closure and uniqueness validation.
    representation_ids = set()
    correspondence_ids = set()
    for anchor in model.get('anchors', {}).values():
        canonical_id = anchor.get('canonical_anchor_id')
        if canonical_id is not None and canonical_id != anchor['id']:
            raise DomainError('INVALID_REFERENCE',
                              'Canonical anchor reference must identify its containing anchor')
        if canonical_id is not None and not anchor.get('representations'):
            raise DomainError('INVALID_REFERENCE',
                              'Canonical anchor must retain a source representation')
        for representation in anchor.get('representations', []):
            ident = representation['id']
            if ident in records:
                raise DomainError('INVALID_REFERENCE', 'Duplicate anchor representation ID')
            records[ident] = representation
            kinds[ident] = 'anchor_representation'
            representation_ids.add(ident)
        for correspondence in anchor.get('correspondences', []):
            ident = correspondence['id']
            if ident in records:
                raise DomainError('INVALID_REFERENCE', 'Duplicate anchor correspondence ID')
            records[ident] = correspondence
            kinds[ident] = 'anchor_correspondence'
            correspondence_ids.add(ident)
    for anchor in model.get('anchors', {}).values():
        for correspondence in anchor.get('correspondences', []):
            candidate_limit = DEFINITIONS['AnchorCorrespondence']['properties'][
                'to_representations']['maxItems']
            if len(correspondence['to_representations']) > candidate_limit:
                raise DomainError('INVALID_REFERENCE',
                                  'Anchor correspondence exceeds the bounded candidate limit')
            represented = {correspondence['from_representation'],
                           *correspondence['to_representations']}
            if not represented <= representation_ids:
                raise DomainError('INVALID_REFERENCE',
                                  'Anchor correspondence refers to a missing representation')
            relationship_edges = correspondence['relationship_edges']
            if not set(relationship_edges) <= set(model.get('edges', {})):
                raise DomainError('INVALID_REFERENCE',
                                  'Anchor correspondence refers to a missing relationship edge')
            if correspondence['state'] == 'resolved' and (
                    len(correspondence['to_representations']) != 1
                    or not correspondence['evidence_ids']
                    or any(model['edges'][edge_id]['resolution'] != 'resolved'
                           for edge_id in relationship_edges)):
                raise DomainError('INVALID_REFERENCE',
                                  'Resolved anchor correspondence requires one target and exact resolved relationship evidence')
    for edge in model.get('edges', {}).values():
        candidates = edge.get('candidate_target_ids', [])
        if edge['resolution'] == 'resolved' and candidates:
            raise DomainError('INVALID_REFERENCE', 'Resolved edge cannot retain alternate candidates')
        if edge['resolution'] == 'ambiguous' and (edge['to_ref'] is not None or len(candidates) < 2):
            raise DomainError('INVALID_REFERENCE', 'Ambiguous edge requires bounded candidate targets')
        if edge['to_ref'] is not None and candidates:
            raise DomainError('INVALID_REFERENCE', 'Selected edge target conflicts with candidate targets')
    referenced_obligations = set()
    for trace in model.get('traces', {}).values():
        if model.get('schema_version', 1) >= 2 and 'obligation_ids' not in trace:
            raise DomainError('INVALID_TRACE', 'Current trace is missing its implementation obligations')
        if 'obligation_ids' in trace:
            referenced_obligations.update(trace['obligation_ids'])
            obligations = [model.get('trace_obligations', {}).get(oid) for oid in trace['obligation_ids']]
            if any(o is None or o['trace_id'] != trace['id'] for o in obligations):
                raise DomainError('INVALID_TRACE', 'Trace obligation is missing or belongs to another trace')
            for obligation in obligations:
                if obligation['origin_ref']['kind'] != 'symbol' or obligation['origin_ref']['id'] not in trace['symbol_ids']:
                    raise DomainError('INVALID_TRACE', 'Trace obligation origin is outside its trace')
                if obligation['edge_id']:
                    if obligation['edge_id'] not in trace['edge_ids']:
                        raise DomainError('INVALID_TRACE', 'Trace obligation edge is outside its trace')
                    edge = model['edges'][obligation['edge_id']]
                    if edge['from_ref'] != obligation['origin_ref']:
                        raise DomainError('INVALID_TRACE', 'Trace obligation origin disagrees with its edge')
            if 'traversal_complete' in trace:
                limited = any(o['status'] == 'limit_reached' for o in obligations)
                if trace['traversal_complete'] == limited:
                    raise DomainError('INVALID_TRACE',
                        'Traversal completion must be independent and consistent with traversal limits')
                if trace['resolution'] == 'resolved' and not trace['traversal_complete']:
                    raise DomainError('INVALID_TRACE', 'A bounded traversal stop cannot be semantic success')
            if model.get('schema_version', 1) >= 2:
                edge_evidence = {evidence_id for edge_id in trace['edge_ids']
                    for evidence_id in model['edges'][edge_id]['evidence_ids']}
                if not edge_evidence <= set(trace['evidence_ids']):
                    raise DomainError('INVALID_EVIDENCE',
                        'Trace omits exact evidence for a reached relationship')
                for edge_id in trace['edge_ids']:
                    edge = model['edges'][edge_id]
                    if edge['kind'] in {'implements', 'inherits', 'has_field',
                            'accepts_type', 'returns_type', 'tests_behavior',
                            'documents_behavior', 'exposes_endpoint',
                            'selects_implementation'}:
                        continue
                    if edge['kind'] in {'reads_data', 'writes_data'}:
                        expected_kind = 'data_target'
                    elif edge['kind'] in {'invokes_endpoint', 'emits'} or (
                            edge['kind'] == 'calls' and edge['to_ref']
                            and edge['to_ref']['kind'] == 'resource'):
                        expected_kind = 'external_boundary'
                    elif edge['resolution'] != 'resolved' or not edge['to_ref']:
                        expected_kind = 'call_target'
                    else:
                        continue
                    matches = [o for o in obligations
                               if o['edge_id'] == edge_id and o['kind'] == expected_kind]
                    if len(matches) != 1:
                        raise DomainError('INVALID_TRACE', 'Trace operation edge requires exactly one typed obligation')
                    obligation = matches[0]
                    if expected_kind == 'external_boundary' and edge['to_ref'] \
                            and obligation['status'] != 'external':
                        raise DomainError('INVALID_TRACE', 'External operation requires an explicit external boundary')
                    if (edge['resolution'] != 'resolved' or not edge['to_ref']) \
                            and obligation['status'] == 'satisfied':
                        raise DomainError('INVALID_TRACE', 'Unresolved operation cannot satisfy its trace obligation')
            if trace['resolution'] == 'resolved' and (
                    not any(o['kind'] == 'implementation_selection' and o['status'] == 'satisfied'
                            and o['candidate_target_ids'] and set(o['candidate_target_ids']) <= set(trace['symbol_ids'])
                            for o in obligations)
                    or any(o['status'] != 'satisfied' for o in obligations)):
                raise DomainError('INVALID_TRACE', 'Resolved trace requires satisfied implementation and capability obligations')
        ui = trace.get('ui_interaction') or {}
        for collection in ('elements', 'events', 'validations', 'calls', 'states', 'transitions', 'outputs'):
            for key, item in ui.get(collection, {}).items():
                if key != item['id'] or key in records:
                    raise DomainError('INVALID_REFERENCE', 'Duplicate UI record ID')
                records[key] = item
                kinds[key] = {'elements':'ui_element','events':'ui_event','states':'ui_state',
                              'outputs':'ui_output'}.get(collection,collection)
    if model.get('schema_version', 1) >= 2 and referenced_obligations != set(model.get('trace_obligations', {})):
        raise DomainError('INVALID_TRACE', 'Every trace obligation must be referenced by exactly one trace')
    retired = {i for change in model.get('identity_changes', []) for i in change['from_ids']}
    def walk(value: Any, parent: str = '') -> None:
        if isinstance(value, dict):
            if set(value) == {'kind', 'id'} and value['id'] not in records:
                raise DomainError('INVALID_REFERENCE', f'Unresolved typed reference in {parent}')
            if set(value) == {'kind','id'} and kinds[value['id']] != value['kind']:
                raise DomainError('INVALID_REFERENCE', f'Wrong reference kind in {parent}')
            for key, item in value.items():
                allowed_kinds = REFERENCE_TARGETS.get(parent+'.'+key,REFERENCE_TARGETS.get(key))
                if allowed_kinds and not (value.get('kind')=='execution_event' and key=='event_id'):
                    targets = item if isinstance(item,list) else ([item] if isinstance(item,str) else [])
                    for ident in targets:
                        if ident not in records or kinds[ident] not in allowed_kinds:
                            raise DomainError('INVALID_REFERENCE',f'Wrong reference kind or missing target in {key}')
                if key.endswith('_ids') and isinstance(item, list):
                    for ident in item:
                        if ident not in records and not (parent == 'identity_changes' and key in ('from_ids','to_ids') and ident in retired):
                            raise DomainError('INVALID_REFERENCE', f'Unresolved reference in {key}')
                elif key.endswith('_id') and isinstance(item, str) and ':' in item and item not in records and not (
                        value.get('kind')=='execution_event' and key=='event_id'):
                    raise DomainError('INVALID_REFERENCE', f'Unresolved reference in {key}')
                walk(item, key)
        elif isinstance(value, list):
            for item in value:
                walk(item, parent)
    walk(model)
    for effect in model.get('effects', {}).values():
        origin = effect.get('origin_ref')
        if not origin:
            if model.get('schema_version', 1) >= 2:
                raise DomainError('INVALID_REFERENCE', 'Current effect is missing its operation origin')
            continue  # Legacy effects predate operation-origin hydration.
        edge_id = effect.get('edge_id')
        if origin['kind'] != 'symbol':
            raise DomainError('INVALID_REFERENCE', 'Effect origin must identify a symbol')
        if model.get('schema_version', 1) >= 2 and not edge_id:
            raise DomainError('INVALID_REFERENCE', 'Current effect is missing its operation edge')
        if edge_id:
            edge = model['edges'][edge_id]
            if edge['from_ref'] != origin or edge['to_ref'] != effect['target']:
                raise DomainError('INVALID_REFERENCE', 'Effect and operation edge disagree on origin or target')
            if not set(edge['evidence_ids']) <= set(effect['evidence_ids']):
                raise DomainError('INVALID_EVIDENCE',
                    'Effect omits the exact evidence for its operation edge')
        reachable = {tid for tid, trace in model.get('traces', {}).items()
                     if origin['id'] in trace['symbol_ids'] and (not edge_id or edge_id in trace['edge_ids'])}
        if set(effect['trace_ids']) != reachable:
            raise DomainError('INVALID_TRACE', 'Effect backlinks must match operation reachability')
        if any(not set(effect['evidence_ids']) <= set(model['traces'][tid]['evidence_ids'])
               for tid in effect['trace_ids']):
            raise DomainError('INVALID_EVIDENCE',
                'Trace omits exact evidence for a reachable effect')
    if model.get('schema_version', 1) >= 2:
        operation_kinds = {'reads_data', 'writes_data', 'invokes_endpoint', 'emits'}
        effects_by_edge = {}
        for effect in model.get('effects', {}).values():
            if effect.get('edge_id'):
                effects_by_edge.setdefault(effect['edge_id'], []).append(effect)
            for field, direction in (('input_binding_ids', 'input'), ('output_binding_ids', 'output')):
                if any(model['bindings'][bid]['direction'] != direction for bid in effect[field]):
                    raise DomainError('INVALID_BINDING', 'Effect binding has the wrong direction', field)
            if any(model['bindings'][bid]['direction'] != 'input'
                   for bid in effect['header_binding_ids']):
                raise DomainError('INVALID_BINDING',
                    'Effect header binding has the wrong direction', 'header_binding_ids')
            if not set(effect['header_binding_ids']) <= set(effect['input_binding_ids']):
                raise DomainError('INVALID_BINDING',
                    'Effect header bindings must be included in its input bindings',
                    'header_binding_ids')
            if effect.get('edge_id') and not set(effect['header_binding_ids']) <= set(
                    model['edges'][effect['edge_id']]['binding_ids']):
                raise DomainError('INVALID_BINDING',
                    'Effect header bindings must be included on its operation edge',
                    'header_binding_ids')
        for edge in model.get('edges', {}).values():
            if edge['kind'] not in operation_kinds:
                continue
            if edge['from_ref']['kind'] != 'symbol' or (edge['to_ref'] and edge['to_ref']['kind'] != 'resource'):
                raise DomainError('INVALID_REFERENCE', 'Operation edge must connect a symbol to a resource')
            if not edge['evidence_ids']:
                raise DomainError('INVALID_EVIDENCE', 'Operation edge requires exact evidence')
            linked = effects_by_edge.get(edge['id'], [])
            if edge['kind'] == 'reads_data' and linked:
                raise DomainError('INVALID_REFERENCE', 'Data reads cannot fabricate effects')
            if edge['kind'] in {'writes_data', 'invokes_endpoint', 'emits'} and len(linked) != 1:
                raise DomainError('INVALID_REFERENCE',
                    'Observable operation edge is missing its effect or has duplicate effects')
            effect_bindings = {bid for effect in linked
                               for field in ('input_binding_ids', 'output_binding_ids',
                                             'header_binding_ids')
                               for bid in effect[field]}
            if linked and set(edge['binding_ids']) != effect_bindings:
                raise DomainError('INVALID_BINDING', 'Operation edge and effect bindings disagree')
            reached = {trace['id'] for trace in model.get('traces', {}).values()
                       if edge['from_ref']['id'] in trace['symbol_ids']}
            if any(edge['id'] not in model['traces'][trace_id]['edge_ids']
                   for trace_id in reached):
                raise DomainError('INVALID_TRACE',
                    'Reachable operation edge is omitted from a trace')
            if edge['resolution'] != 'resolved' and not any(
                    edge['id'] in warning['subject_ids']
                    and set(edge['evidence_ids']) <= set(warning['evidence_ids'])
                    for warning in model.get('warnings', [])):
                raise DomainError('INVALID_REFERENCE',
                    'Unresolved operation is missing its hydration diagnostic')
        for activity in model.get('activities', {}).values():
            for field, expected in activity_closure(model, activity).items():
                if set(activity[field]) != expected:
                    raise DomainError('INVALID_REFERENCE', 'Activity operation closure is incomplete or contains unrelated work', field)
        for use in model.get('information_uses', {}).values():
            closure = information_use_closure(model, use)
            for field in ('trace_ids', 'binding_ids', 'effect_ids'):
                if set(use[field]) != closure[field]:
                    raise DomainError('INVALID_REFERENCE', 'Information-use operation closure is incomplete or unrelated', field)
            if not closure['evidence_ids'] <= set(use['evidence_ids']):
                raise DomainError('INVALID_EVIDENCE', 'Information use omits operation evidence', 'evidence_ids')
            if use['resolution'] == 'resolved' and (any(
                    model['edges'][eid]['resolution'] != 'resolved' for eid in closure['edge_ids']) or any(
                    model['effects'][eid]['resolution'] != 'resolved' for eid in closure['effect_ids'])):
                raise DomainError('INVALID_REFERENCE',
                    'Resolved information use requires resolved operation facts', 'resolution')
    primary: set[str] = set()
    for domain in model.get('domains', {}).values():
        for member in domain['activity_memberships']:
            if member['role'] == 'primary':
                if member['activity_id'] in primary:
                    raise DomainError('INVALID_MEMBERSHIP', 'Activity has multiple primary domains')
                primary.add(member['activity_id'])
    for activity in model.get('activities', {}).values():
        for direction in ('input', 'output'):
            for ident in activity[direction + '_binding_ids']:
                if model['bindings'][ident]['direction'] != direction:
                    raise DomainError('INVALID_BINDING', 'Activity binding has the wrong direction')


def read_json(path: Path, max_bytes: int = 25000000) -> dict | None:
    if not path.exists():
        return None
    if path.is_symlink() or any(parent.is_symlink() for parent in path.parents) or not path.is_file() or path.stat().st_size > max_bytes:
        raise DomainError('INVALID_ARTIFACT', 'Unsafe or oversized artifact')
    try:
        with path.open('rb') as stream:
            raw = stream.read(max_bytes+1)
        if len(raw)>max_bytes:
            raise DomainError('INVALID_ARTIFACT','Unsafe or oversized artifact')
        value = json.loads(raw)
    except DomainError:
        raise
    except (ValueError, UnicodeError, OSError) as exc:
        raise DomainError('INVALID_ARTIFACT', 'Unreadable JSON artifact') from exc
    if not isinstance(value, dict):
        raise DomainError('INVALID_ARTIFACT', 'Artifact must be a JSON object')
    return value


def quarantine_file(path: Path, directory: Path,
                    max_bytes: int = 25000000) -> Path | None:
    """Atomically remove an invalid authority while retaining its exact bytes."""
    if not path.exists():
        return None
    if (path.is_symlink() or any(parent.is_symlink() for parent in path.parents)
            or not path.is_file() or path.stat().st_size > max_bytes):
        raise DomainError('INVALID_ARTIFACT', 'Unsafe or oversized artifact')
    raw = path.read_bytes()
    if len(raw) > max_bytes:
        raise DomainError('INVALID_ARTIFACT', 'Unsafe or oversized artifact')
    directory.mkdir(parents=True, exist_ok=True)
    if directory.is_symlink() or any(parent.is_symlink() for parent in directory.parents):
        raise DomainError('UNSAFE_PATH', 'Artifact quarantine contains a symlink')
    target = directory / f'{path.stem}-{digest(raw)}.invalid{path.suffix}'
    os.replace(path, target)
    return target


_LEGACY_STATUS_LIMIT_FIELDS = frozenset({
    'max_activities', 'max_evidence_per_packet', 'activities_used',
})
_POST_LEGACY_STATUS_LIMIT_FIELDS = frozenset({
    'token_estimator', 'provider_context_tokens', 'provider_max_output_tokens',
    'effective_request_input_tokens', 'effective_request_output_tokens',
    'semantic_units_total', 'semantic_units_validated', 'semantic_units_cached',
    'semantic_units_active', 'semantic_units_failed', 'semantic_units_pending',
    'model_ready_graph_tokens', 'completion_input_tokens_reserved',
    'completion_output_tokens_reserved',
})


def _migrate_legacy_status_limits(value: dict) -> dict | None:
    """Translate the one pre-accounting Limits shape without widening other artifacts."""
    legacy = value.get('limits')
    if value.get('schema_version') != 1 or not isinstance(legacy, dict):
        return None
    current = DEFINITIONS['Limits']
    current_fields = set(current['properties'])
    legacy_fields = set(legacy)
    if not _LEGACY_STATUS_LIMIT_FIELDS <= legacy_fields:
        return None
    if legacy_fields - current_fields - _LEGACY_STATUS_LIMIT_FIELDS:
        return None
    if (set(current['required']) - _POST_LEGACY_STATUS_LIMIT_FIELDS) - legacy_fields:
        return None

    retained = {key: copy.deepcopy(item) for key, item in legacy.items()
                if key in current_fields}
    retained.update({
        'token_estimator': ACCOUNTING_POLICY['token_estimator'],
        'provider_context_tokens': None,
        'provider_max_output_tokens': None,
        'effective_request_input_tokens': legacy['max_request_input_tokens'],
        'effective_request_output_tokens': legacy['max_request_output_tokens'],
        'semantic_units_total': 0,
        'semantic_units_validated': 0,
        'semantic_units_cached': 0,
        'semantic_units_active': 0,
        'semantic_units_failed': 0,
        'semantic_units_pending': 0,
        'model_ready_graph_tokens': 0,
        'completion_input_tokens_reserved': 0,
        'completion_output_tokens_reserved': 0,
    })
    migrated = copy.deepcopy(value)
    migrated['limits'] = retained
    return migrated


def read_status(path: Path, max_bytes: int = 25000000) -> dict | None:
    """Read a status, migrating only the recognized legacy Limits payload."""
    value = read_json(path, max_bytes)
    if value is None:
        return None
    try:
        validate(value, 'StatusArtifact')
        return value
    except DomainError:
        migrated = _migrate_legacy_status_limits(value)
        if migrated is None:
            raise
        validate(migrated, 'StatusArtifact')
        return migrated


def validate_evidence(root: Path, model: dict, max_bytes: int = 25000000) -> None:
    """Verify stored excerpt provenance without rescanning the repository."""
    root = root.resolve()
    blobs = {}
    for evidence in model['evidence'].values():
        if digest(evidence['excerpt'].encode()) != evidence['content_hash']:
            raise DomainError('INVALID_EVIDENCE','Evidence excerpt hash mismatch')
        locator = evidence['locator']
        snapshot = model['source_snapshots'].get(locator.get('snapshot_id'))
        if not snapshot:
            raise DomainError('INVALID_EVIDENCE','Evidence snapshot is missing')
        path = root/snapshot['local_blob_path']
        if not path.resolve().is_relative_to(root):
            raise DomainError('INVALID_EVIDENCE','Snapshot is outside repository containment')
        if path not in blobs:
            blob = read_json(path,max_bytes)
            if not blob:
                raise DomainError('INVALID_EVIDENCE','Snapshot blob is missing')
            validate(blob,'SnapshotArtifact'); blobs[path] = blob
        blob = blobs[path]
        if blob['source_hash'] != snapshot['content_hash'] or blob['snapshot_id'] != snapshot['id']:
            raise DomainError('INVALID_EVIDENCE','Snapshot identity/hash mismatch')
        value = blob
        try:
            for token in locator['pointer'].lstrip('/').split('/'):
                token = token.replace('~1','/').replace('~0','~')
                value = value[int(token)] if isinstance(value,list) else value[token]
        except (KeyError,IndexError,ValueError,TypeError) as exc:
            raise DomainError('INVALID_EVIDENCE','Snapshot evidence pointer is invalid') from exc
        if value != evidence['excerpt']:
            raise DomainError('INVALID_EVIDENCE','Snapshot excerpt differs from cited evidence')


def atomic_write(path: Path, value: dict, max_bytes: int = 25000000) -> None:
    data = canonical(value)
    if len(data) > max_bytes:
        raise DomainError('ARTIFACT_LIMIT', 'Artifact exceeds configured byte limit')
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink() or any(parent.is_symlink() for parent in path.parents if parent != path.anchor):
        raise DomainError('UNSAFE_PATH', 'Artifact path contains a symlink')
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def copy_facts(facts: dict, build_id: str) -> dict:
    model = record('DomainArtifact', **copy.deepcopy(facts))
    model.update(build_id=build_id, facts_build_id=facts['build_id'], status='partial')
    return model
